// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OurBrosAPI.Data;

#nullable disable

namespace OurBrosAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231110170208_null-enabled lobby model")]
    partial class nullenabledlobbymodel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("OurBrosAPI.Data.Models.Lobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("lobbyname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("lobbyowner")
                        .HasColumnType("TEXT");

                    b.Property<string>("lobbypassword")
                        .HasColumnType("TEXT");

                    b.Property<int?>("usercount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Lobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            lobbyname = "Lobby1"
                        },
                        new
                        {
                            Id = 2,
                            lobbyname = "Lobby2"
                        },
                        new
                        {
                            Id = 3,
                            lobbyname = "lobby3"
                        });
                });

            modelBuilder.Entity("OurBrosAPI.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("userpassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            username = "TestUser1",
                            userpassword = "1234"
                        },
                        new
                        {
                            Id = 2,
                            username = "TestUser2",
                            userpassword = "1234"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
